/*
  SUPABASE SETUP
  1. Create a Supabase project.
  2. Create table "portfolio_reviews":
       id bigint generated by default as identity primary key
       rating int not null check (rating between 1 and 5)
       message text
       created_at timestamptz default now()
  3. Enable RLS and allow anonymous SELECT + INSERT only as appropriate.
  4. Put your project URL and publishable/anon key below.
  Supabase's browser client can be loaded from CDN.
*/
const SUPABASE_URL="YOUR_SUPABASE_URL";
const SUPABASE_ANON_KEY="YOUR_SUPABASE_ANON_KEY";
let supabaseClient=null;
let selectedRating=0;

const stars=document.querySelectorAll("#starsInput button");
stars.forEach(star=>star.addEventListener("click",()=>{
 selectedRating=Number(star.dataset.rating);
 stars.forEach(s=>s.classList.toggle("selected",Number(s.dataset.rating)<=selectedRating));
}));

async function initSupabase(){
 const status=document.getElementById("reviewStatus");
 if(SUPABASE_URL.startsWith("YOUR_")||SUPABASE_ANON_KEY.startsWith("YOUR_")){
   status.textContent="Supabase not configured yet — add your project credentials in js/supabase.js.";
   return;
 }
 const script=document.createElement("script");
 script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";
 script.onload=async()=>{
   supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
   await loadRatings();
 };
 script.onerror=()=>status.textContent="Could not load Supabase client.";
 document.head.appendChild(script);
}
async function loadRatings(){
 const {data,error}=await supabaseClient.from("portfolio_reviews").select("rating");
 if(error){document.getElementById("reviewStatus").textContent="Could not load reviews.";return}
 const count=data.length;
 const avg=count?data.reduce((sum,r)=>sum+r.rating,0)/count:0;
 document.getElementById("averageRating").textContent=count?avg.toFixed(1):"—";
 document.getElementById("reviewCount").textContent=count?`${count} review${count===1?"":"s"}`:"No reviews yet";
}
document.getElementById("submitReview").addEventListener("click",async()=>{
 const status=document.getElementById("reviewStatus");
 if(!selectedRating){status.textContent="Please select a star rating first.";return}
 if(!supabaseClient){status.textContent="Supabase is not configured yet. Your selection was not sent.";return}
 const message=document.getElementById("reviewMessage").value.trim();
 const {error}=await supabaseClient.from("portfolio_reviews").insert({rating:selectedRating,message});
 if(error){status.textContent="Review could not be submitted. Check your Supabase RLS policy.";return}
 status.textContent="Thank you for the review!";
 document.getElementById("reviewMessage").value="";
 selectedRating=0;stars.forEach(s=>s.classList.remove("selected"));await loadRatings();
});
initSupabase();
